version: '3.9'
x-backend-base: &backend-base
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - './config/nginx-related/:/usr/local/openresty/nginx/conf/conf/'
    - './nginx-backend.conf:/usr/local/openresty/nginx/conf/nginx.conf'
    - './src/:/lua/src/'

x-edge-base: &edge-base
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - './config/nginx-related/:/usr/local/openresty/nginx/conf/conf/'
    - './nginx-edge.conf:/usr/local/openresty/nginx/conf/nginx.conf'
    - './src/:/lua/src/'

services:
  backend1:
    <<: *backend-base
    container_name: backend1
    ports:
      - '8080:8080'

  backend2:
    <<: *backend-base
    container_name: backend2
    ports:
      - '8180:8080'

  edge1:
    <<: *edge-base
    container_name: edge1
    ports:
      - '8081:8080'

  edge2:
    <<: *edge-base
    container_name: edge2
    ports:
      - '8082:8080'

  edge3:
    <<: *edge-base
    container_name: edge3
    ports:
      - '8083:8080'

  load-balancer:
    container_name: load-balancer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './config/nginx-related/:/usr/local/openresty/nginx/conf/conf/'
      - './nginx-load-balancer.conf:/usr/local/openresty/nginx/conf/nginx.conf'
      - './src/:/lua/src/'
    depends_on:
      - edge1
      - edge2
      - edge3
    ports:
      - "18080:8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=24h'
      - '--web.enable-lifecycle'
    labels:
      org.label-schema.group: 'monitoring'
    depends_on:
      - backend1
      - backend2
      - edge1
      - edge2
      - edge3
      - load-balancer
    ports:
      - '9090:9090'

  grafana:
    user: root
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    links:
      - prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - '9091:3000'

