version: "3.9"
services:
  base:
    image: igorbarinov/openresty-nginx-module-vts
    volumes:
      - "./config/nginx-related/:/usr/local/openresty/nginx/conf/conf/"
      - "./src/:/lua/src/"

  backend:
    extends:
      service: base
    volumes:
      - "./nginx-backend.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports:
      - "8080:8080"

  edge:
    extends:
      service: base
    volumes:
      - "./nginx-edge.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./edge/:/cache/"
    depends_on:
      - backend
    ports:
      - "8081:8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    restart: unless-stopped
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    links:
      - prometheus
    ports:
      - "9091:3000"

