version: '3.9'

x-base: &base
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - './config/nginx-related/:/usr/local/openresty/nginx/conf/conf/'
    - './src/:/lua/src/'
    - './nginx-backend-traditional.conf:/usr/local/openresty/nginx/conf/nginx.conf'

services:
  backend1:
    <<: *base
    container_name: backend1-old
    ports:
      - '8080:8080'

  backend2:
    <<: *base
    container_name: backend2-old
    ports:
      - '8081:8080'

  # load-balancer:
  #   <<: *base
  #   container_name: load-balancer-old
  #   volumes:
  #     - './nginx-load-balancer-traditional.conf:/usr/local/openresty/nginx/conf/nginx.conf'
  #   depends_on:
  #     - backend1
  #     - backend2
  #   ports:
  #     - '18080:8080'