x-base: &base
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - './config/nginx-related/:/usr/local/openresty/nginx/conf/conf/'
    - './src/:/lua/src/'
    - './nginx-backend-trad.conf:/usr/local/openresty/nginx/conf/nginx.conf'

services:
  backend1-trad:
    <<: *base
    container_name: backend1-trad
    ports:
      - '8080:8080'

  backend2-trad:
    <<: *base
    container_name: backend2-trad
    ports:
      - '8081:8080'
  
  load-balancer-trad:
    container_name: load-balancer-trad
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './config/nginx-related/:/usr/local/openresty/nginx/conf/conf/'
      - './nginx-load-balancer-trad.conf:/usr/local/openresty/nginx/conf/nginx.conf'
      - './src/:/lua/src/'
    depends_on:
      - backend1-trad
      - backend2-trad
    ports:
      - "18080:8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus-trad.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=24h'
      - '--web.enable-lifecycle'
    labels:
      org.label-schema.group: 'monitoring'
    depends_on:
      - backend1-trad
      - backend2-trad
    ports:
      - '9090:9090'

  grafana:
    user: root
    image: grafana/grafana:10.2.2
    container_name: grafana
    restart: unless-stopped
    links:
      - prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - '9091:3000'