version: "3.9"
services:
  base:
    image: igorbarinov/openresty-nginx-module-vts
    volumes:
      - "./conf/cache-define.conf:/usr/local/openresty/nginx/conf/cache-define.conf"
      - "./conf/cache-setup.conf:/usr/local/openresty/nginx/conf/cache-setup.conf"
      - "./conf/vts-location.conf:/usr/local/openresty/nginx/conf/vts-location.conf"
      - "./conf/vts-setup.conf:/usr/local/openresty/nginx/conf/vts-setup.conf"
      - "./conf/lua-path.conf:/usr/local/openresty/nginx/conf/lua-path.conf"
      - "./src/:/lua/src/"

  backend:
    extends:
      service: base
    volumes:
      - "./nginx-backend.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports:
      - "8080:8080"

  edge:
    extends:
      service: base
    volumes:
      - "./nginx-edge.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./edge/:/cache/"
    depends_on:
      - backend
    ports:
      - "8081:8080"

