version: '3.9'
services:
  base:
    image: igorbarinov/openresty-nginx-module-vts
    volumes:
      - './config/nginx-related/:/usr/local/openresty/nginx/conf/conf/'
      - './src/:/lua/src/'

  backend:
    extends:
      service: base
    volumes:
      - './nginx-backend.conf:/usr/local/openresty/nginx/conf/nginx.conf'
    ports:
      - '8080:8080'

  edge:
    extends:
      service: base
    volumes:
      - './nginx-edge.conf:/usr/local/openresty/nginx/conf/nginx.conf'
      - './edge/:/cache/'
    depends_on:
      - backend
    ports:
      - '8081:8080'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=24h'
      - '--web.enable-lifecycle'
    labels:
      org.label-schema.group: 'monitoring'
    ports:
      - '9090:9090'

  grafana:
    user: root
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    links:
      - prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - '9091:3000'