global:
  scrape_interval: 10s
  external_labels:
    monitor: 'CDN'

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/status/format/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'cdn-thesis-loadbalancer:8080'
        - 'cdn-thesis-edge1:8080'
        - 'cdn-thesis-edge2:8080'
        - 'cdn-thesis-edge3:8080'
        - 'cdn-thesis-backend1:8080'
        - 'cdn-thesis-backend2:8080'
