global:
  scrape_interval: 10s
  external_labels:
    monitor: 'CDN'

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/status/format/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['cdn-thesis-edge-1:8080', 'cdn-thesis-backend-1:8080']
