global:
  scrape_interval:     10s
  evaluation_interval: 10s
  scrape_timeout:      2s

  external_labels:
    monitor: 'cdn'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['edge:8080', 'backend:8080']
